######################################################################
# Automatically generated by qmake (3.0) ven. nov. 18 14:17:45 2016
######################################################################

TEMPLATE = app
TARGET = work
INCLUDEPATH += . /usr/include/irrlicht

# Input
HEADERS += events.h \
    character.h
SOURCES += events.cpp main.cpp \
    character.cpp
